config/routes.rb
Hulmefestival::Application.routes.draw do
  resources :adverts do
    member do
      get 'position'
      get 'payment'
      post 'pay'
    end
  end

  root :to => "adverts#index"

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  attr_accessible :image, :url, :x_position, :y_position, :text
  has_attached_file :image, :url => "/adverts/:id/:style/:basename.:extension",  
    :path => ":rails_root/public/adverts/:id/:style/:basename.:extension"  

  validates_presence_of :text, :url, :image
  
  def validate
    if self.image.queued_for_write[:original]
      image_dimensions = Paperclip::Geometry.from_file(self.image.queued_for_write[:original])
      if (image_dimensions.width % 10) != 0
        self.errors.add(:image, "Please ensure your advert's width is a multiple of 10")
      end
      
      if (image_dimensions.height % 10) != 0
        self.errors.add(:image, "Please ensure your advert's height is a multiple of 10")
      end
    end
  end
  
  def before_initialize
    self.paid = false
  end
  
  def pay
    self.paid = true
    self.save
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  # GET /adverts
  # GET /adverts.xml
  def index
    @adverts = Advert.find_all_by_paid(true)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adverts }
    end
  end


  # GET /adverts/new
  # GET /adverts/new.xml
  def new
    @advert = Advert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @advert }
    end
  end

  # POST /adverts
  # POST /adverts.xml
  def create
    @advert = Advert.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to(position_advert_path(@advert), :notice => 'Advert was successfully created.') }
        format.xml  { render :xml => @advert, :status => :created, :location => @advert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @advert.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def position
    @advert = Advert.find_by_id(params[:id])
    @adverts = Advert.find_all_by_paid(true)
  end
  
  def payment
    @advert = Advert.find_by_id(params[:id])
    @adverts = Advert.find_all_by_paid(true)
    @adverts << @advert
  end
  
  def pay
    @advert = Advert.find_by_id(params[:id])
    @advert.pay
    respond_to do |format|
      format.html { redirect_to(adverts_path) }
    end
    
  end

  # PUT /adverts/1
  # PUT /adverts/1.xml
  def update
    @advert = Advert.find(params[:id])

    respond_to do |format|
      if @advert.update_attributes(params[:advert])
        if params["advert"]["x_position"] && params["advert"]["y_position"]
          format.html { redirect_to(payment_advert_path(@advert)) }
        else
          format.html { redirect_to(@advert, :notice => 'Advert was successfully updated.') }
          format.xml  { head :ok }
        end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @advert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.xml
  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to(adverts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adverts/_form.html.erb
<%= form_for @advert, :html => { :multipart => true } do |f| %>
  <% if @advert.errors.any? %>
    <div id="error_explanation">
      <h2>Something went wrong :\</h2>

      <ul>
      <% @advert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <p>
      <%= f.label :text, "Name of your organisation / event:" %><br />
      <%= f.text_field :text %>
    </p>
  </div>
  <div class="field">
    <p>
      <%= f.label :url, "Your webpage url:" %><br />
      <%= f.text_field :url %>
    </p>
  </div>
  <div class="field">
    <p>
      <%= f.label :image, "Your image / logo (size must be a multiple of 10):" %><br />
       <%= f.file_field :image %>
    </p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adverts/_wall_view.html.erb
<script type="application/javascript">
  var adverts = [
    <% @adverts.each do |advert| %>
      [<%= advert.x_position -%>, <%= advert.y_position -%>,"<%= advert.text -%>","<%= advert.url -%>","<%= advert.image.url -%>"]<% unless advert == @adverts.last %>,<% end %>
    <% end %>
  ]
  
  var context;
  var canvas;

  function init() {
    canvas = $('#canvas')[0]
    context = canvas.getContext("2d");
    canvas.addEventListener("mousemove", drawAdvertTextAtPosition, false);
    canvas.addEventListener("mouseout", draw, false);
    canvas.addEventListener("click", goToAdvertURLAtPosition, false);
    clear();
    loadAndDrawImages();
  }

  function getMousePosition(e) {
    var x;
    var y;
    if (e.pageX || e.pageY) { 
      x = e.pageX;
      y = e.pageY;
    }
    else { 
      x = e.clientX + document.body.scrollLeft + document.documentElement.scrollLeft; 
      y = e.clientY + document.body.scrollTop + document.documentElement.scrollTop; 
    } 
    x -= $('#canvas')[0].offsetLeft;
    y -= $('#canvas')[0].offsetTop;
    return [x,y]
  }

  function advertIndexAtPosition(xPosition, yPosition) {
    for (advert in adverts) {
      // if horizontal position is within the horizontal bounds of another image
      if (xPosition >= adverts[advert][0] && xPosition < adverts[advert][0] + images[advert].width) {
        // if vertical position is within the vertical bounds of another image
        if (yPosition >= adverts[advert][1] && yPosition < adverts[advert][1] + images[advert].height) {
          console.log(advert);
          return advert;
        }
      }
    }
    return -1;
    console.log(-1);
  }

  function goToAdvertURLAtPosition(e) {
    var mousePosition = getMousePosition(e);
    var xPosition = Math.floor(mousePosition[0]/10)*10;
    var yPosition = Math.floor(mousePosition[1]/10)*10;
    var advertIndex = advertIndexAtPosition(xPosition, yPosition);
    if (advertIndex >= 0) {
      window.open(adverts[advertIndex][3], adverts[advertIndex][2]);
    }
  }

  function drawAdvertTextAtPosition(e) {
    var mousePosition = getMousePosition(e);
    var xPosition = Math.floor(mousePosition[0]/10)*10;
    var yPosition = Math.floor(mousePosition[1]/10)*10;
    var advertIndex = advertIndexAtPosition(xPosition, yPosition);
    if (advertIndex >= 0) {
      clear();
      draw();
      context.font = "bold 12px helvetica";
      var textWidth = context.measureText(adverts[advertIndex][2]).width;
      context.fillStyle = "#EBE6D1";
      context.strokeStyle = "333A58";

      var horizontalOffset = 0;
      if (mousePosition[0] > (canvas.width / 2)) {
        horizontalOffset = -textWidth;
      }

      context.fillRect(mousePosition[0] + horizontalOffset, mousePosition[1] - 10, textWidth, 12);
      context.strokeRect(mousePosition[0] + horizontalOffset, mousePosition[1] - 10, textWidth, 12);
      context.fillStyle = "#333A58";
      context.fillText(adverts[advertIndex][2], mousePosition[0] + horizontalOffset, mousePosition[1]);
    }
    else {
      draw();
    }
  }

  var images = [];
  var loadedImageCount = 0;
  function loadAndDrawImages() {
    loadedImageCount = 0;
    for (advert in adverts) {
      console.log(advert);
      images[advert] = new Image();
      images[advert].src = adverts[advert][4];
      images[advert].onload = imageLoaded;
    }
  }

  function clear() {
    context.clearRect(0, 0, canvas.width, canvas.height);
  }

  function draw() {
    clear();
    drawImages();
  }

  function imageLoaded() {
    loadedImageCount ++;
    if (loadedImageCount >= adverts.length) {
      imagesLoaded = true;
      drawImages();
    }
  }

  function drawImages() {
    for (image in images) {
      context.drawImage(images[image], adverts[image][0], adverts[image][1]);
    }
  }
</script>

app/views/adverts/index.html.erb
<% content_for :viewSpecificHeader do %>
  <script type="application/javascript">
    var adverts = [
      <% @adverts.each do |advert| %>
        [<%= advert.x_position %>, <%= advert.y_position %>,"<%= advert.text %>","<%= advert.url %>","<%= advert.image.url %>"]<% unless advert == @adverts.last%>,<% end %>
      <% end %>
    ]
  </script>
  <script type="application/javascript" src="/javascripts/wall-view.js"></script>
<% end %>

<div>
  <canvas id="canvas" class="donor-wall" width="639" height="419" ></canvas>
</div>

<div class="text center">
  <p>
    <%= link_to "Click here to advertise online and onsite.", new_advert_path %>
  </p>
  </p>
</div>

<div class="text center">
  <p>Continue to the Hulme Festival Website.</p>
  </p>
</div>

app/views/adverts/new.html.erb
<div class="text center">
  <p>Please enter the details of your advertisement below.</p>
  </p>
</div>

<div class="text center">
  <p>Before submitting please make sure your image width and height are a multiple of ten. </p>
  </p>
</div>

<div class="text center">
  <p>Adverts are charged at £1 per 10 x 10 pixel square.</p>

  <p>So a 20 by 20 pixel advert will cost £4</p>

  <p>And a 60 by 50 pixel advert will cost £30</p>  
</div>


<div class="text center alt">
  <p>
    <%= render 'form' %>
 </p>
</div>

app/views/adverts/payment.html.erb
<% content_for :viewSpecificHeader do %>
  <script type="application/javascript">
    var adverts = [
      <% @adverts.each do |advert| %>
        [<%= advert.x_position %>, <%= advert.y_position %>,"<%= advert.text %>","<%= advert.url %>","<%= advert.image.url %>"]<% unless advert == @adverts.last%>,<% end %>
      <% end %>
    ]
  </script>
  <script type="application/javascript" src="/javascripts/wall-view.js"></script>
<% end %>

<div>
  <canvas id="canvas" class="donor-wall" width="639" height="419" ></canvas>
</div>

<div class="text center">
  <p>This is a preview of what your advert will look like. When you hover over it it will show you your text, and when you click on it it will open a window to your URL. If you are happy with this, please click the button below to pay.</p>
  </p>
</div>

<div class="text center">
  <p>
    <% form_tag pay_advert_path(@advert), :method => :post do %>
      <%= submit_tag 'Click here to pay' %>
    <% end %>
  </p>
</div>

app/views/adverts/position.html.erb
<% content_for :viewSpecificHeader do %>
  <script type="application/javascript">
    var adverts = [
      <% @adverts.each do |advert| %>
        [<%= advert.x_position %>, <%= advert.y_position %>,"<%= advert.text %>","<%= advert.url %>","<%= advert.image.url %>"]<% unless advert == @adverts.last%>,<% end %>
      <% end %>
    ]
    
    var imageCursor = new Image();
    imageCursor.src = "<%= @advert.image.url %>";
  </script>
  <script type="application/javascript" src="/javascripts/wall-position.js"></script>
<% end %>

<div>
  <canvas id="canvas" class="donor-wall" width="639" height="419" ></canvas>
</div>

<% form_for @advert, :html => { :id => 'setPosition' } do |f| %>
  <%= f.hidden_field :x_position %>
  <%= f.hidden_field :y_position %>
<% end %>

<div class="text center">
  <p>Click on the grid to position your advert, or <a id="position-automatically" href="#">click here</a> to position your advert automatically.</p>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Hulme Festival</title>
	<meta name="author" content="Becky Conning">
	<link rel="stylesheet" type="text/css" href="/stylesheets/main.css" />
	<script type="application/javascript" src="/javascripts/jquery.js"></script>
	<%= yield :viewSpecificHeader %>
	<!-- Date: 2011-04-11 -->
</head>
<body>
  <div class="bunting"></div>
  <div class="container outer">
    <div>
     <div class="header">
       <img src="/images/header.png" alt="Hulme Festival!"/>    
     </div>
     <div class="header">
      <img src="/images/art.png" alt="Art" />
      <img src="/images/seperator.png" alt="Art" />
      <img src="/images/music.png" alt="Art" />
      <img src="/images/seperator.png" alt="Art" />
      <img src="/images/workshops.png" alt="Art" />
      <img src="/images/seperator.png" alt="Art" />
      <img src="/images/food.png" alt="Art" />
    </div>
    </div>
    <div class="clear"></div>

<%= yield %>

    <img src="/images/logos.png" alt="
      Venture Arts, 
      Zion Arts, 
      Hulme Community Garden Centre, 
      City South Manchester Housing Trust,
      Barclays,
      The Big Life Group,
      Manchester Creative Collective,
      X Trax,
      Manchester City Council
    "/>
  </div>
</body>
</html>